name: MyAction

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        build-root-directory: app
    - name: publish code coverage
      uses: paambaati/codeclimate-action@v3.2.0
      env: 
        CC_TEST_REPORTER_ID: ${{secrets.TESTCOVERAGE}}
        JACOCO_SOURCE_PATH: src/main/java
      with:
        coverageCommand: make report 
        coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:xml
