name: MyAction

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        build-root-directory: app/
    - name: make build
      run: | 
        cd app/
        make build
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.2.0
      env: 
        CC_TEST_REPORTER_ID: ${{secrets.TESTCOVERAGE}}
        JACOCO_SOURCE_PATH: "${{github.workspace}}app/src/main/java"
      with:
        coverageCommand: ./gradlew test 
        coverageLocations: ${{github.workspace}}app/target/site/jacoco/jacoco.xml:jacoco
